services:
  attendance-app:
    image: ghcr.io/keledaikedelaikeledai/attendance-app:latest
    container_name: atd-demo
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "7070:3000" # Optional: expose locally for debugging
    environment:
      # Add your app-specific env vars here
      NODE_ENV: production
    env_file:
      - .env.production # Load environment variables from a file
    depends_on:
      - postgres

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    restart: unless-stopped
    command: tunnel run # Or tunnel --config /etc/cloudflared/config.yml if using a named tunnel
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - internal
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    networks:
      - internal
    environment:
      POSTGRES_DB: atdstag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  internal:
    driver: bridge
