version: '3.8'
services:
  app:
    build: .
    image: attendance-app:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      # Set any runtime envs your app needs here, e.g.:
      NODE_ENV: production
      # Use a local sqlite file inside the container (persisted in ./data on the host)
      NUXT_DB_URL: "file:sqlite.db"
    volumes:
      # Persist DB in a host folder and bind the sqlite file into the container
      - ./data:/data:rw
      - ./data/sqlite.db:/app/sqlite.db:rw

  cloudflared:
    image: cloudflare/cloudflared:2025.9.1
    restart: unless-stopped
    depends_on:
      - app
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    environment:
      # Provide your tunnel token in environment or via docker secrets
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared:ro

# Notes:
# - Set CLOUDFLARED_TUNNEL_TOKEN in your environment or in an env-file before running
# - cloudflared will create the tunnel and route traffic to the local app port (3000)